config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "static_pages#top"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[new create]
  resources :default_vocabularies, only: %i[index show]
  resources :bookmarks, only: %i[index create destroy]
  resources :vocabularies, only: %i[show new create edit update destroy]
  resources :tasks, only: %i[index]
  resources :password_resets, only: %i[new create edit update]
  
  resources :categories, only: [:new, :create, :destroy] do
    get :delete_confirm, on: :collection
  end

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :default_vocabulary

  validates :user_id, uniqueness: { scope: :default_vocabulary_id }
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @category = Category.where(user_id: current_user.id)
    @category_with_defaults = {}
    @category_with_vocabularies = {}
    @category.each do |category|
      @category_with_defaults[category] = current_user.bookmarks.includes(:default_vocabulary).where(category_id: category.id).order(created_at: :desc).map(&:default_vocabulary)
      @category_with_vocabularies[category] = Vocabulary.where(category_id: category.id).order(created_at: :desc)
    end

    # カテゴリーがない場合にフラグを設定
    @no_categories = @category.empty?
  end

  def create
    default_vocabulary = DefaultVocabulary.find(params[:default_vocabulary_id])
    category_id = params[:category_id]
    current_user.bookmark(default_vocabulary, category_id)
    redirect_to default_vocabularies_path, success: "リストに追加しました"
  end

  def destroy
    default_vocabulary = current_user.bookmarks.find(params[:id]).default_vocabulary
    current_user.unbookmark(default_vocabulary)
    redirect_to default_vocabularies_path, success: "リストから削除しました", status: :see_other
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/index.html.erb
<h1>My会話帳</h1>
  <div class="container">
    <div class="row">
      <div class="d-flex flex-column flex-sm-row justify-content-sm-end">
        <div class="text-center mb-3 mb-sm-0">
          <%= link_to new_vocabulary_path, class: "btn btn-primary me-4" do %>
            単語の作成
          <% end %>
        </div>
        <div class="text-center mb-3 mb-sm-0">
          <%= link_to new_category_path, class: "btn btn-outline-secondary vv me-3" do %>
            カテゴリーの追加
          <% end %>
          <%= link_to delete_confirm_categories_path, class: "btn btn-outline-secondary colr" do %>
            カテゴリーの削除
          <% end %>
        </div>
      </div>
    </div>
  </div>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <% @category.each_with_index do |category, index| %>
    <li class="nav-item" role="presentation">
      <button class="nav-link <%= index == 0 ? 'active' : '' %>" id="<%= "tab-#{category.id}" %>" data-bs-toggle="tab" data-bs-target="#<%= "tab-pane-#{category.id}" %>" type="button" role="tab" aria-controls="<%= "tab-pane-#{category.id}" %>" aria-selected="<%= index == 0 ? 'true' : 'false' %>">
        <%= category.name %>
      </button>
    </li>
  <% end %>
</ul>
<div class="tab-content" id="myTabContent">
  <% @category.each_with_index do |category, index| %>
    <div class="tab-pane fade<%= index == 0 ? ' show active' : '' %>" id="<%= "tab-pane-#{category.id}" %>" role="tabpanel" aria-labelledby="<%= "tab-#{category.id}" %>" tabindex="0">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col" style="width: 5%;"></th>
              <th scope="col" style="width: 5%;"></th>
              <th scope="col" style="width: 20%;">単語</th>
              <th scope="col" style="width: 20%;">ボポモフォ</th>
              <th scope="col" style="width: 30%;">意味</th>
              <th scope="col" style="width: 10%;"></th>
              <th scope="col" style="width: 10%;"></th>
            </tr>
          </thead>
          <tbody>
            <% index = 1 %>
            <% @category_with_defaults[category].each do |default_vocabulary| %>
              <tr>
                <th scope="row" style="white-space: nowrap;"><%= index %></th>
                <td style="white-space: nowrap;"><button id="playButton" type="button" class="btn btn-light btn-icon"><i class="bi bi-volume-up"></i></button></td>
                <td style="white-space: nowrap;"><%= default_vocabulary.title %></td>
                <td style="white-space: nowrap;"><%= default_vocabulary.bopomofo %></td>
                <td style="white-space: nowrap;"><%= default_vocabulary.mean %></td>
                <td style="white-space: nowrap;">
                  <%= link_to default_vocabulary_path(default_vocabulary) do %>
                    <button type="button" class="btn btn-secondary">詳細</button>
                  <% end %>
                </td>
                <td style="white-space: nowrap;"></td>
              </tr>
              <% index += 1 %>
            <% end %>
              <!-- vocabulariesテーブルのデータを表示する部分 -->
            <% @category_with_vocabularies[category].each do |vocabulary| %>
              <tr>
                <th scope="row" style="white-space: nowrap;"><%= index %></th>
                <td style="white-space: nowrap;"><button id="playButton" type="button" class="btn btn-light btn-icon"><i class="bi bi-volume-up"></i></button></td>
                <td style="white-space: nowrap;"><%= vocabulary.title %></td>
                <td style="white-space: nowrap;"><%= vocabulary.bopomofo %></td>
                <td style="white-space: nowrap;"><%= vocabulary.mean %></td>
                <td style="white-space: nowrap;">
                  <%= link_to vocabulary_path(vocabulary) do %>
                    <button type="button" class="btn btn-secondary">詳細</button>
                  <% end %>
                </td>
                <td style="white-space: nowrap;">
                  <% if current_user.own?(vocabulary) %>
                  <div class="ms-auto">
                    <%= link_to edit_vocabulary_path(vocabulary), id: "button-edit-#{vocabulary.id}" do %>
                      <i class="bi bi-pencil-fill"></i>
                    <% end %>
                    <%= link_to vocabulary_path(vocabulary), id: "button-delete-#{vocabulary.id}", data: { turbo_method: :delete, turbo_confirm: '削除しますか' } do %>
                      <i class="bi bi-trash-fill"></i>
                    <% end %>
                  </div>
                <% end %>
                </td>
              </tr>
              <% index += 1 %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>
<div class="saize">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8 mx-auto">
        <% if @no_categories %>
          <div class="alert alert-info">
            まだカテゴリーが作成されていません。まずはカテゴリーを作成しましょう。
          </div>
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
              <div class="card mb-4 mx-auto ff">
                <%= image_tag 'phrasebooksumaho.jpg', class: 'card-img-top' %>
                <div class="card-body">
                  <h5 class="card-title">①まずは、カテゴリーを追加しましょう</h5>
                  <p class="card-text">単語や文章を分ける為のカテゴリーを作成できます。</p>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="card mb-4 mx-auto ff">
                <%= image_tag 'phrasebooksumaho2.jpg', class: 'card-img-top' %>
                <div class="card-body">
                  <h5 class="card-title">②ブックマーク機能</h5>
                  <p class="card-text">既存の単語をブックマークし、「My会話帳」に追加できます。</p>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="card mb-4 mx-auto ff">
                <%= image_tag 'phrasebooksumaho3.jpg', class: 'card-img-top' %>
                <div class="card-body">
                  <h5 class="card-title">③単語作成機能</h5>
                  <p class="card-text">「My会話帳」に入れたい単語や文章を作成し、追加できます。</p>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <!-- ここに既存のカテゴリーがある場合の表示を記述 -->
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
 document.addEventListener("turbo:load", function() {
  // ボタン要素を取得
  var playButtons = document.querySelectorAll('.btn-light');

  // イベントリスナーをクリア
  playButtons.forEach(function(playButton) {
    playButton.removeEventListener('click', playButtonClickHandler);
  });

  // ボタンがクリックされたときのイベントリスナーを再登録
  playButtons.forEach(function(playButton) {
    playButton.addEventListener('click', playButtonClickHandler);
  });
});

function playButtonClickHandler() {
  // 親要素(tr)を取得
  var row = this.closest('tr');

  // テーブルの <td> 要素を取得
  var titleCell = row.querySelector('td:nth-child(3)');

  // タイトルのテキストを取得
  var text = titleCell.textContent.trim();

  // Web Speech API を使用してテキストを読み上げる
  var utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = 'zh-CN';
  speechSynthesis.speak(utterance);
}
</script>

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 col-lg-8 mx-auto">
      <h1>カテゴリーの選択</h1>
      <%= form_with model: @category, class: "new_board" do |f| %>
        <div class="mb-3">
          <%= f.label :カテゴリー名 %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <%= f.submit "追加", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>