config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "static_pages#top"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[new create]
  resources :default_vocabularies, only: %i[index show]
  resources :bookmarks, only: %i[index create destroy]
  resources :vocabularies, only: %i[show new create edit update destroy]
  resources :tasks, only: %i[index]
  resources :password_resets, only: %i[new create edit update]
  
  resources :categories, only: [:new, :create, :destroy] do
    get :delete_confirm, on: :collection
  end

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/default_vocabulary.rb
class DefaultVocabulary < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :bopomofo, presence: true, length: { maximum: 255 }
  validates :mean, presence: true, length: { maximum: 255 }

  has_many :bookmarks, dependent: :destroy
end

app/controllers/default_vocabularies_controller.rb
class DefaultVocabulariesController < ApplicationController
  skip_before_action :require_login, only: [:show]
  
  def index
    target_category = Category.find_by(name: '日常生活')
    @default_vocabularies = DefaultVocabulary.where(category_id: target_category.id)  
    target_category1 = Category.find_by(name: 'ビジネス')
    @default_vocabularies1 = DefaultVocabulary.where(category_id: target_category1.id)
    target_category2 = Category.find_by(name: '数')
    @default_vocabularies2 = DefaultVocabulary.where(category_id: target_category2.id)
    target_category3 = Category.find_by(name: '月・曜日・時制')
    @default_vocabularies3 = DefaultVocabulary.where(category_id: target_category3.id)
    target_category4 = Category.find_by(name: '人')
    @default_vocabularies4 = DefaultVocabulary.where(category_id: target_category4.id)
    target_category5 = Category.find_by(name: '場所')
    @default_vocabularies5 = DefaultVocabulary.where(category_id: target_category5.id)
    target_category6 = Category.find_by(name: 'もの')
    @default_vocabularies6 = DefaultVocabulary.where(category_id: target_category6.id)
  end

  def show
    @default_vocabulary = DefaultVocabulary.find(params[:id])
  end
end

app/views/default_vocabularies/_default_vocabularies_table.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col" style="width: 5%;"></th>
        <th scope="col" style="width: 5%;"></th>
        <th scope="col" style="width: 20%;">単語</th>
        <th scope="col" style="width: 20%;">ボポモフォ</th>
        <th scope="col" style="width: 30%;">意味</th>
        <th scope="col" style="width: 10%;"></th>
        <th scope="col" style="width: 10%;"></th>
      </tr>
    </thead>
    <% index = 1 %>
    <tbody>
      <% default_vocabularies.each do |default_vocabulary| %>
        <tr>
          <th scope="row" style="white-space: nowrap;"><%= index %></th>
          <td style="white-space: nowrap;"><button id="playButton" type="button" class="btn btn-light btn-icon"><i class="bi bi-volume-up"></i></button></td>
          <td style="white-space: nowrap;"><%= default_vocabulary.title %></td>
          <td style="white-space: nowrap;"><%= default_vocabulary.bopomofo %></td>
          <td style="white-space: nowrap;"><%= default_vocabulary.mean %></td>
          <td style="white-space: nowrap;">
            <% if current_user.bookmark?(default_vocabulary) %>
              <%= link_to bookmark_path(current_user.bookmarks.find_by(default_vocabulary_id: default_vocabulary.id)), data: { turbo_method: :delete } do %>
                <button type="button" class="btn btn-outline-secondary">My会話帳から削除</button>
              <% end %>
            <% else %>
              <div class="accordion" id="bookmarkForm<%= default_vocabulary.id %>">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="bookmarkFormHeading<%= default_vocabulary.id %>">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#bookmarkFormCollapse<%= default_vocabulary.id %>" aria-expanded="false" aria-controls="bookmarkFormCollapse<%= default_vocabulary.id %>">
                      My会話帳に追加
                    </button>
                  </h2>
                  <div id="bookmarkFormCollapse<%= default_vocabulary.id %>" class="accordion-collapse collapse" aria-labelledby="bookmarkFormHeading<%= default_vocabulary.id %>" data-bs-parent="#bookmarkForm<%= default_vocabulary.id %>">
                    <div class="accordion-body">
                      <%= form_with url: bookmarks_path, method: :post, local: true do |f| %>
                        <div class="mb-3">
                          <%= f.label :category_id, "カテゴリー" %>
                          <% if current_user.categories.blank? %>
                            <%= f.collection_select :category_id, current_user.categories, :id, :name, {}, {class: "form-control"} %>
                            <p class="text-danger" style="font-size: 0.9em;" >My会話帳から<br>カテゴリーの追加をしてください。</p>
                          <% else %>
                            <%= f.collection_select :category_id, current_user.categories, :id, :name, {}, {class: "form-control"} %>
                          <% end %>
                        </div>
                        <%= f.hidden_field :default_vocabulary_id, value: default_vocabulary.id %>
                        <%= f.submit "追加", class: "btn btn-outline-secondary" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </td>
          <td style="white-space: nowrap;">
            <%= link_to default_vocabulary_path(default_vocabulary) do %>
              <button type="button" class="btn btn-secondary">詳細</button>
            <% end %>
          </td>
        </tr>
        <% index += 1 %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/default_vocabularies/index.html.erb
<h1>Phrases</h1>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active tabbak-color" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">日常生活</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link tabbak2-color" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">ビジネス</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
    <%= render partial: 'default_vocabularies_table', locals: { default_vocabularies: @default_vocabularies } %>
  </div>
  <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
    <%= render partial: 'default_vocabularies_table', locals: { default_vocabularies: @default_vocabularies1 } %>
  </div>
</div>

<h1>Words</h1>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active tabbak3-color" id="ome-tab" data-bs-toggle="tab" data-bs-target="#ome-tab-pane" type="button" role="tab" aria-controls="ome-tab-pane" aria-selected="true">数</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link tabbak3-color" id="rofile-tab" data-bs-toggle="tab" data-bs-target="#rofile-tab-pane" type="button" role="tab" aria-controls="rofile-tab-pane" aria-selected="false">月・曜日・時制</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link tabbak3-color" id="ontact-tab" data-bs-toggle="tab" data-bs-target="#ontact-tab-pane" type="button" role="tab" aria-controls="ontact-tab-pane" aria-selected="false">人</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link tabbak3-color" id="place-tab" data-bs-toggle="tab" data-bs-target="#place-tab-pane" type="button" role="tab" aria-controls="place-tab-pane" aria-selected="false">場所</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link tabbak3-color" id="thing-tab" data-bs-toggle="tab" data-bs-target="#thing-tab-pane" type="button" role="tab" aria-controls="thing-tab-pane" aria-selected="false">もの</button>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="ome-tab-pane" role="tabpanel" aria-labelledby="ome-tab" tabindex="0">
    <%= render partial: 'default_vocabularies_table', locals: { default_vocabularies: @default_vocabularies2 } %>
  </div>
  <div class="tab-pane fade" id="rofile-tab-pane" role="tabpanel" aria-labelledby="rofile-tab" tabindex="0">
    <%= render partial: 'default_vocabularies_table', locals: { default_vocabularies: @default_vocabularies3 } %>
  </div>
  <div class="tab-pane fade" id="ontact-tab-pane" role="tabpanel" aria-labelledby="ontact-tab" tabindex="0">
    <%= render partial: 'default_vocabularies_table', locals: { default_vocabularies: @default_vocabularies4 } %>
  </div>
  <div class="tab-pane fade" id="place-tab-pane" role="tabpanel" aria-labelledby="place-tab" tabindex="0">
    <%= render partial: 'default_vocabularies_table', locals: { default_vocabularies: @default_vocabularies5 } %>
  </div>
  <div class="tab-pane fade" id="thing-tab-pane" role="tabpanel" aria-labelledby="thing-tab" tabindex="0">
    <%= render partial: 'default_vocabularies_table', locals: { default_vocabularies: @default_vocabularies6 } %>
  </div>
</div>

<script>
 document.addEventListener("turbo:load", function() {
  // ボタン要素を取得
  var playButtons = document.querySelectorAll('.btn-light');

  // イベントリスナーをクリア
  playButtons.forEach(function(playButton) {
    playButton.removeEventListener('click', playButtonClickHandler);
  });

  // ボタンがクリックされたときのイベントリスナーを再登録
  playButtons.forEach(function(playButton) {
    playButton.addEventListener('click', playButtonClickHandler);
  });
});

function playButtonClickHandler() {
  // 親要素(tr)を取得
  var row = this.closest('tr');

  // テーブルの <td> 要素を取得
  var titleCell = row.querySelector('td:nth-child(3)');

  // タイトルのテキストを取得
  var text = titleCell.textContent.trim();

  // Web Speech API を使用してテキストを読み上げる
  var utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = 'zh-CN';
  speechSynthesis.speak(utterance);
}
</script>

app/views/default_vocabularies/show.html.erb
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1>詳細</h1>
      <article class="card">
        <div class="card-body">
          <div class="row justify-content-center">
            <div class="col-md-9">
              <div class="border-bottom mb-3 pb-2">
                <div style="font-size: 1.4rem;" >台湾華語</div>
                <div style="font-size: 1.8rem;"><%= @default_vocabulary.title %></div>
              </div>
              <div class="border-bottom mb-3 pb-2">
                <div style="font-size: 1.4rem;">ボポモフォ</div>
                <div style="font-size: 1.8rem;"><%= @default_vocabulary.bopomofo %></div>
              </div>
              <div class="border-bottom mb-3 pb-2">
                <div style="font-size: 1.4rem;">意味</div>
                <div style="font-size: 1.8rem;"><%= @default_vocabulary.mean %></div>
              </div>
              <div class="border-bottom mb-3 pb-2">
                <div style="font-size: 1.4rem;">説明</div>
                <div style="font-size: 1.8rem;"> <p><%= simple_format(@default_vocabulary.body) %></p></div>
              </div>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>