config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "static_pages#top"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[new create]
  resources :default_vocabularies, only: %i[index show]
  resources :bookmarks, only: %i[index create destroy]
  resources :vocabularies, only: %i[show new create edit update destroy]
  resources :tasks, only: %i[index]
  resources :password_resets, only: %i[new create edit update]
  
  resources :categories, only: [:new, :create, :destroy] do
    get :delete_confirm, on: :collection
  end

  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :default_vocabulary

  validates :user_id, uniqueness: { scope: :default_vocabulary_id }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }

  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :vocabularies, dependent: :destroy
end

app/models/default_vocabulary.rb
class DefaultVocabulary < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :bopomofo, presence: true, length: { maximum: 255 }
  validates :mean, presence: true, length: { maximum: 255 }

  has_many :bookmarks, dependent: :destroy
end

app/models/task_completion.rb
class TaskCompletion < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :user_id, uniqueness: { scope: :date }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, format: {
  with: /\A(?=.*[a-z])(?=.*[A-Z])|(?=.*[a-z])(?=.*\d)|(?=.*[a-z])(?=.*[@$!%*?&])|(?=.*[A-Z])(?=.*\d)|(?=.*[A-Z])(?=.*[@$!%*?&])|(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,32}\z/,
  message: "は8文字から32文字で、英小文字、英大文字、数字、およびスペース以外の記号から2種以上を含む必要があります。",
  if: -> { new_record? || changes[:crypted_password] }
  }

  validates :password, exclusion: { in: ->(user) { [user.email, user.email.split('@').first, user.email.split('@').last] }, message: "にはメールアドレスを含めることはできません。" }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_defaults, through: :bookmarks, source: :default_vocabulary
  has_many :categories, dependent: :destroy
  has_many :vocabularies, dependent: :destroy
  has_many :task_completions, dependent: :destroy

  def own?(object)
    self.id == object.user_id #selfは省略できる
  end

  def bookmark(default_vocabulary)
    bookmarked_defaults << default_vocabulary
  end

  def unbookmark(default_vocabulary)
    bookmarked_defaults.destroy(default_vocabulary)
  end

  def bookmark?(default_vocabulary)
    bookmarked_defaults.include?(default_vocabulary)
  end

  def bookmark(default_vocabulary, category_id)
    bookmarks.create(default_vocabulary: default_vocabulary, category_id: category_id)
  end
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :bopomofo, presence: true, length: { maximum: 255 }
  validates :mean, presence: true, length: { maximum: 255 }
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @category = Category.where(user_id: current_user.id)
    @category_with_defaults = {}
    @category_with_vocabularies = {}
    @category.each do |category|
      @category_with_defaults[category] = current_user.bookmarks.includes(:default_vocabulary).where(category_id: category.id).order(created_at: :desc).map(&:default_vocabulary)
      @category_with_vocabularies[category] = Vocabulary.where(category_id: category.id).order(created_at: :desc)
    end

    # カテゴリーがない場合にフラグを設定
    @no_categories = @category.empty?
  end

  def create
    default_vocabulary = DefaultVocabulary.find(params[:default_vocabulary_id])
    category_id = params[:category_id]
    current_user.bookmark(default_vocabulary, category_id)
    redirect_to default_vocabularies_path, success: "リストに追加しました"
  end

  def destroy
    default_vocabulary = current_user.bookmarks.find(params[:id]).default_vocabulary
    current_user.unbookmark(default_vocabulary)
    redirect_to default_vocabularies_path, success: "リストから削除しました", status: :see_other
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    # Date.todayをUTCに合わせる
    today_jst = Time.zone.today

    @word_created_today = current_user.last_vocabulary_created_at.present? && current_user.last_vocabulary_created_at.to_date == today_jst
    @logged_in_today = logged_in?
    # @logged_in_todayの以前の記述logged_in? && current_user.last_login_at.present? && current_user.last_login_at.to_date == today_jst

    @both_conditions_met = @logged_in_today && @word_created_today

    if @both_conditions_met
      TaskCompletion.find_or_create_by(user: current_user, date: today_jst)
    end
    @task_completions = current_user.task_completions.pluck(:date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: "ユーザー登録が完了しました"
    else
      flash.now[:danger] = "ユーザー登録に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>台湾華語会話帳</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" integrity="sha384-XGjxtQfXaH2tnPFa9x+ruJTuLE3Aa6LhHSWRr1XeTyhezb4abCG4ccI5AkVDxqC+" crossorigin="anonymous">
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-53GDDHSH');</script>
    <!-- End Google Tag Manager -->
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-RYG7QLYD7M"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-RYG7QLYD7M');
    </script>
  </head>

  <body>
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-53GDDHSH"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  <title>タイトルだよ</title>
   <div class="containef">
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <div class="spese"></div>
    <%= render 'shared/footer' %>
   </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script>
       // 固定ヘッダーのアニメーションを処理する関数
      function FixedAnime() {
        var headerH = $('.top-wrapper').outerHeight(true);
        var scroll = $(window).scrollTop();
        if (scroll >= headerH) { // ヘッダーの高さ以上にスクロールしたら
          $('.menu-color').addClass('fixed'); // fixedクラスを追加
        } else {
          $('.menu-color').removeClass('fixed'); // fixedクラスを除去
        }
      }

      // デバイスがモバイルかどうかを確認する関数
      function isMobileDevice() {
        return window.innerWidth <= 599;
      }

      // スクロール時に固定ヘッダーアニメーションを実行（モバイルデバイスの場合のみ）
      $(window).scroll(function () {
        if (isMobileDevice()) {
          FixedAnime(); // モバイルデバイスの場合のみ関数を呼び出す
        }
      });

      // ページロード時に固定ヘッダーアニメーションを実行（モバイルデバイスの場合のみ）
      $(window).on('load', function () {
        if (isMobileDevice()) {
          FixedAnime(); // モバイルデバイスの場合のみ関数を呼び出す
        }
      });

      // リサイズ時に固定ヘッダーアニメーションを実行（モバイルデバイスの場合のみ）
      $(window).on('resize', function () {
        if (isMobileDevice()) {
          FixedAnime(); // モバイルデバイスの場合のみ関数を呼び出す
        } else {
          $('.menu-color').removeClass('fixed'); // デスクトップの場合はfixedクラスを除去
        }
      });
    </script>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <div class='top-wrapper'>
  </div>
  <nav class="navbar navbar-expand-lg navigation navbar-dark menu-color">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to 'ログイン', login_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_bopomofo_keyboard.html.erb
<div class="keyboard mb-3">
    <!-- ボポモフォのキー -->
    <!-- 第一列 -->
    <div class="key" onclick="typeKey('ㄅ')">ㄅ</div>
    <div class="key" onclick="typeKey('ㄆ')">ㄆ</div>
    <div class="key" onclick="typeKey('ㄇ')">ㄇ</div>
    <div class="key" onclick="typeKey('ㄈ')">ㄈ</div>
    <div class="key" onclick="typeKey('ㄉ')">ㄉ</div>
    <div class="key" onclick="typeKey('ㄊ')">ㄊ</div>
    <div class="key" onclick="typeKey('ㄋ')">ㄋ</div>
    <div class="key" onclick="typeKey('ㄌ')">ㄌ</div>
    <div class="key" onclick="typeKey('ㄍ')">ㄍ</div>
    <div class="key" onclick="typeKey('ㄎ')">ㄎ</div>
    <div class="key" onclick="typeKey('ㄏ')">ㄏ</div>

    <!-- 第二列 -->
    <div class="key" onclick="typeKey('ㄐ')">ㄐ</div>
    <div class="key" onclick="typeKey('ㄑ')">ㄑ</div>
    <div class="key" onclick="typeKey('ㄒ')">ㄒ</div>
    <div class="key" onclick="typeKey('ㄓ')">ㄓ</div>
    <div class="key" onclick="typeKey('ㄔ')">ㄔ</div>
    <div class="key" onclick="typeKey('ㄕ')">ㄕ</div>
    <div class="key" onclick="typeKey('ㄖ')">ㄖ</div>
    <div class="key" onclick="typeKey('ㄗ')">ㄗ</div>
    <div class="key" onclick="typeKey('ㄘ')">ㄘ</div>
    <div class="key" onclick="typeKey('ㄙ')">ㄙ</div>

    <!-- 第三列 -->
    <div class="key" onclick="typeKey('ㄚ')">ㄚ</div>
    <div class="key" onclick="typeKey('ㄛ')">ㄛ</div>
    <div class="key" onclick="typeKey('ㄜ')">ㄜ</div>
    <div class="key" onclick="typeKey('ㄝ')">ㄝ</div>
    <div class="key" onclick="typeKey('ㄞ')">ㄞ</div>
    <div class="key" onclick="typeKey('ㄟ')">ㄟ</div>
    <div class="key" onclick="typeKey('ㄠ')">ㄠ</div>
    <div class="key" onclick="typeKey('ㄡ')">ㄡ</div>
    <div class="key" onclick="typeKey('ㄢ')">ㄢ</div>
    <div class="key" onclick="typeKey('ㄣ')">ㄣ</div>
    <div class="key" onclick="typeKey('ㄤ')">ㄤ</div>
    <div class="key" onclick="typeKey('ㄥ')">ㄥ</div>
    <div class="key" onclick="typeKey('ㄦ')">ㄦ</div>

    <!-- 第四列 -->
    <div class="key" onclick="typeKey('ㄧ')">ㄧ</div>
    <div class="key" onclick="typeKey('ㄨ')">ㄨ</div>
    <div class="key" onclick="typeKey('ㄩ')">ㄩ</div>
    <div class="key" onclick="typeKey('ˊ')">ˊ</div>
    <div class="key" onclick="typeKey('ˇ')">ˇ</div>
    <div class="key" onclick="typeKey('ˋ')">ˋ</div>
    <div class="key" onclick="typeKey('˙')">˙</div>
    <!-- 他のボポモフォキーを追加 -->
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer py-4 border-top">
  <div class="container">
    <div class="row">
      <div class="col-md-6 custom-margin">
        <div class='copyright'>
          <p class="mb-0 text-muted">Copyright © 2024. TaiwanKago</p>
        </div>
      </div>
      <div class="col-md-6">
        <ul class="list-unstyled d-flex flex-column flex-md-row justify-content-md-end mb-0">
          <li class="mb-2 mb-md-0 ms-md-3"><%= link_to 'プライバシーポリシー', privacy_policy_path, class: "text-muted text-decoration-none text-hover-dark" %></li>
          <li class="ms-md-3"><%= link_to '利用規約', terms_of_service_path, class: "text-muted text-decoration-none text-hover-dark" %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class='top-wrapper'>
  </div>
  <nav class='navbar navbar-expand-lg navigation navbar-dark menu-color'>
    <%= link_to default_vocabularies_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item'>
          <%= link_to 'Basic Phrases / Words', default_vocabularies_path, class: 'nav-link' %>
        </li>

         <li class='nav-item'>
          <%= link_to '今日の課題', tasks_path, class: 'nav-link' %>
        </li>

        <li class='nav-item'>
          <%= link_to 'My会話帳', bookmarks_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'ログアウト', logout_path, class: 'nav-link', data: { turbo_method: :delete } %>
        </li>
      </ul>
    </div>
  </nav>
</header>